default_platform(:ios)

platform :ios do
  lane :upload_store_assets do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_API_KEY_ID"],
      issuer_id: ENV["ASC_API_KEY_ISSUER_ID"],
      key_filepath: "/tmp/AuthKey.p8"
    )

    deliver(
      api_key: api_key,
      app_identifier: "com.luisserranol.fraterna",
      skip_binary_upload: true,
      screenshots_path: "./store-assets/screenshots",
      metadata_path: "./store-assets/metadata",
      overwrite_screenshots: true,
      submit_for_review: false,
      force: true
    )
  end
end
